blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns= [
   path('',views.PostList.as_view(),name='post_list'),
   path('<slug:slug>',views.PostDetail.as_view(),name='post_detail'),
]

chatbotpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('chatbotapp.urls'))

]

labs/urls.py
from django.urls import path
from . import views

app_name = 'labs'

urlpatterns = [
    path('', views.LabList.as_view(), name='lab_list'),
    path('unity_lab/<int:lab_id>/', views.unity_lab, name='unity_lab'),
    path('<slug:slug>',views.LabDetail.as_view(),name='lab_detail'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # accounts must be at first of all
    path('accounts/', include('django.contrib.auth.urls')), # User Auth
    path('accounts/', include('accounts.urls', namespace='accounts')), # Profile
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')), # summernote package for text editor in admin
    path('', include('settings.urls', namespace='home')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('labs/', include('labs.urls', namespace='labs')),
    path('blog/', include('blog.urls', namespace='blog')),

    # social account
    path('socialaccounts/', include('allauth.urls')),

    path('verification/', include('verify_email.urls')), # verify pkg


]

# settings for static and media roots
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labs/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.

### labs
class Lab(models.Model):
   title = models.CharField(max_length=50)
   description = models.TextField(max_length=20000)
   created_at = models.DateTimeField(default=timezone.now)
   image = models.ImageField(upload_to='images/')
   youtube_url = models.URLField(max_length = 200,null=True)
   experiment_objective = models.TextField(max_length=1000,null=True)
   experiment_materials = models.TextField(max_length=1000,null=True)
   experiment_steps = models.TextField(max_length=1000,null=True)
   experiment_conclusion = models.TextField(max_length=1000,null=True)
   # doc_file = models.FileField(upload_to='doc_files/')

   # FK
   category = models.ForeignKey('Category', related_name='lab_category', on_delete=models.CASCADE)

   # feature (slug) for url with title of post_detail
   slug = models.SlugField(null=True, blank=True)
   # for slug - save slug field = title of post
   def save(self, *args, **kwargs):
       if not self.slug:
          self.slug = slugify(self.title)
        # Call the real save() method
       super(Lab, self).save(*args, **kwargs)

   def __str__(self):
       return self.title

   def get_absolute_url(self):
       return reverse('labs:lab_detail',args=[str(self.slug)])



class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

labs/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from .models import Category, Lab
from settings.forms import SubscriberForm
# Create your views here.

class LabList(ListView):# gets the ListView from django
    model = Lab # model data
    paginate_by = 3 # pagination

    # return subscriber form in footer
    def get_context_data(self, **kwargs): # return another data
        context = super().get_context_data(**kwargs)
        context["subscriber_form"] = SubscriberForm()
        return context

class LabDetail(DetailView):# gets the DetailView from django
    model = Lab

    # return subscriber form in footer
    def get_context_data(self, **kwargs): # return another data
        context = super().get_context_data(**kwargs)
        context["subscriber_form"] = SubscriberForm()
        return context

def unity_lab(request,lab_id):# renders the unity page
    return render(request, f'labs/index{lab_id}.html',{})#the link redirects depending on the desired lab

labs/templates/labs/index1.html
<!DOCTYPE html>
{% load static %}
<html lang="en-us">

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Unity WebGL Player | URP_lap</title>
    <link rel="shortcut icon" href='{% static "TemplateData/favicon.ico" %}'>
    <link rel="stylesheet" href='{% static "TemplateData/style.css" %}'>
    <link rel="stylesheet" href='{% static "TemplateData/unity.css" %}'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src='{% static "TemplateData/UnityProgress.js" %}'></script>
    <script src='{% static "TemplateData/unity.js" %}'></script>
    <script src='{% static "Build/UnityLoader.js" %}'></script>


    <script>
        var unityInstance = UnityLoader.instantiate("unityContainer",'{% static "Build/V2.json" %}', {
            onProgress: UnityProgress
        });

    </script>


</head>


<body>

    <div class="webgl-content  responsive">
        <div id="unityContainer" class="" ></div>
        <div class="footer">
            <!-- <button type="button" class="btn btn-primary btn-md" onclick="startLive()" id="start">start live</button> -->
            <button class="btn btn-primary btn-lg"  onclick="openForm()"  >startLive</button>

              <!-- <div class="fullscreen" onclick="unityInstance.SetFullscreen(1)"></div> -->
            <button type="button" class="btn btn-secondary btn-lg"  onclick="closeForm()">stopLive</button>        </div>

    </div>


    <div class="" id="myForm">
      <div class="form-container">

       <!-- <div class="embed-responsive embed-responsive-16by9"  id="display" style="width: 400px; height: 300px;">
        <iframe class="embed-responsive-item"  src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen></iframe>
      </div> -->
      <div class="embed-responsive embed-responsive-16by9" id="display" style="width: 400px; height: 300px;">
        <iframe class="embed-responsive-item" src="http://197.166.102.138:8080" allowfullscreen></iframe>
    </div>


    </div>
    </div>

    <!-- <div class="embed-responsive embed-responsive-16by9" id="display" style="width: auto; height: auto;">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen></iframe>
      </div> -->


    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>

</html>

labs/templates/labs/index10.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Unity WebGL Player | URP_lap</title>
    <link rel="shortcut icon" href='{% static "TemplateData2/favicon.ico" %}'>
    <link rel="stylesheet" href='{% static "TemplateData2/style.css" %}'>
    <link rel="stylesheet" href='{% static "TemplateData2/stylation.css" %}'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src='{% static "TemplateData2/unity.js" %}'></script>

  </head>
  <body>
    <div id="unity-container" class="unity-desktop">
      <canvas id="unity-canvas" width=960 height=600></canvas>
      <div id="unity-loading-bar">
        <div id="unity-logo"></div>
        <div id="unity-progress-bar-empty">
          <div id="unity-progress-bar-full"></div>
        </div>
      </div>
      <div id="unity-mobile-warning">
        WebGL builds are not supported on mobile devices.
      </div>
      <div id="unity-footer">
        <!-- <div id="unity-webgl-logo"></div> -->
        <div id="unity-fullscreen-button"></div>
        <!-- <div id="unity-build-title">URP_lap</div> -->

        <button class="btn btn-primary btn-lg"  onclick="openForm()"  >startLive</button>
        <button type="button" class="btn btn-secondary btn-lg"  onclick="closeForm()">stopLive</button>

      </div>
    </div>

    <div class="" id="myForm">
      <div class="form-container">

       <!-- <div class="embed-responsive embed-responsive-16by9"  id="display" style="width: 400px; height: 300px;">
        <iframe class="embed-responsive-item"  src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen></iframe>
      </div> -->
      <div class="embed-responsive embed-responsive-16by9" id="display" style="width: 400px; height: 300px;">
        <iframe class="embed-responsive-item" src="http://197.166.79.134:8080" allowfullscreen></iframe>
    </div>


    </div>
    </div>


    <script>
      var buildUrl ='{% static  "Build2" %}';
      var loaderUrl = buildUrl + "/levelExprement.loader.js";
      var config = {
        dataUrl: buildUrl + "/levelExprement.data",
        frameworkUrl: buildUrl + "/levelExprement.framework.js",
        codeUrl: buildUrl + "/levelExprement.wasm",
        streamingAssetsUrl: "StreamingAssets",
        companyName: "DefaultCompany",
        productName: "URP_lap",
        productVersion: "1.0",
      };

      var container = document.querySelector("#unity-container");
      var canvas = document.querySelector("#unity-canvas");
      var loadingBar = document.querySelector("#unity-loading-bar");
      var progressBarFull = document.querySelector("#unity-progress-bar-full");
      var fullscreenButton = document.querySelector("#unity-fullscreen-button");
      var mobileWarning = document.querySelector("#unity-mobile-warning");

      // By default Unity keeps WebGL canvas render target size matched with
      // the DOM size of the canvas element (scaled by window.devicePixelRatio)
      // Set this to false if you want to decouple this synchronization from
      // happening inside the engine, and you would instead like to size up
      // the canvas DOM size and WebGL render target sizes yourself.
      // config.matchWebGLToCanvasSize = false;

      if (/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)) {
        container.className = "unity-mobile";
        // Avoid draining fillrate performance on mobile devices,
        // and default/override low DPI mode on mobile browsers.
        config.devicePixelRatio = 1;
        mobileWarning.style.display = "block";
        setTimeout(() => {
          mobileWarning.style.display = "none";
        }, 5000);
      } else {
        canvas.className = "responsive"
        // canvas.style.height = "600px";
      }
      loadingBar.style.display = "block";

      var script = document.createElement("script");
      script.src = loaderUrl;
      script.onload = () => {
        createUnityInstance(canvas, config, (progress) => {
          progressBarFull.style.width = 100 * progress + "%";
        }).then((unityInstance) => {
          loadingBar.style.display = "none";
          fullscreenButton.onclick = () => {
            unityInstance.SetFullscreen(1);
          };
        }).catch((message) => {
          alert(message);
        });
      };
      document.body.appendChild(script);
    </script>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>



  </body>
</html>

labs/templates/labs/index11.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Unity WebGL Player | URP_lap</title>
    <link rel="shortcut icon" href='{% static "TemplateData3/favicon.ico" %}'>
    <link rel="stylesheet" href='{% static "TemplateData3/style.css" %}'>
    <script src='{% static "TemplateData3/UnityProgress.js" %}'></script>
    <script src='{% static "Build3/UnityLoader.js" %}'></script>
    <link rel="stylesheet" href='{% static "TemplateData3/stylation.css" %}'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src='{% static "TemplateData3/unity.js" %}'></script>

   <script>
      var unityInstance = UnityLoader.instantiate("unityContainer", '{% static "Build3/buildedEXE.json" %}', {onProgress: UnityProgress});
    </script>
  </head>
  <body>
    <div class="webgl-content responsive">
      <div id="unityContainer"></div>
      <div class="footer">
        <!-- <div class="webgl-logo"></div> -->
        <button class="btn btn-primary btn-lg"  onclick="openForm()"  >startLive</button>

        <div class="fullscreen" onclick="unityInstance.SetFullscreen(1)"></div>
        <!-- <div class="title">URP_lap</div> -->
        <button type="button" class="btn btn-secondary btn-lg"  onclick="closeForm()">stopLive</button>

      </div>
    </div>

    <div class="" id="myForm">
      <div class="form-container">

       <!-- <div class="embed-responsive embed-responsive-16by9"  id="display" style="width: 400px; height: 300px;">
        <iframe class="embed-responsive-item"  src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen></iframe>
      </div> -->
      <div class="embed-responsive embed-responsive-16by9" id="display" style="width: 400px; height: 300px;">
        <iframe class="embed-responsive-item" src="http://197.166.79.134:8080" allowfullscreen></iframe>
    </div>


    </div>
    </div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>



  </body>
</html>

labs/templates/labs/index2.html
<h1>resha el gamed</h1>

labs/templates/labs/index9.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Unity WebGL Player | ZU_laboratory</title>
    <link rel="shortcut icon" href='{% static "TemplateData1/favicon.ico" %}'>
    <link rel="stylesheet" href='{% static "TemplateData1/style.css" %}'>
    <link rel="stylesheet" href='{% static "TemplateData1/stylation.css" %}'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src='{% static "TemplateData1/unity.js" %}'></script>

  </head>
  <body>
    <div id="unity-container" class="unity-desktop">
      <canvas id="unity-canvas" width=1024 height=760></canvas>
      <div id="unity-loading-bar">
        <div id="unity-logo"></div>
        <div id="unity-progress-bar-empty">
          <div id="unity-progress-bar-full"></div>
        </div>
      </div>
      <div id="unity-mobile-warning">
        WebGL builds are not supported on mobile devices.
      </div>
      <div id="unity-footer">
        <!-- <div id="unity-webgl-logo"></div> -->
        <div id="unity-fullscreen-button"></div>
        <!-- <div id="unity-build-title">ZU_laboratory</div> -->

        <button class="btn btn-primary btn-lg"  onclick="openForm()"  >startLive</button>
        <button type="button" class="btn btn-secondary btn-lg"  onclick="closeForm()">stopLive</button>


      </div>
    </div>


    <div class="" id="myForm">
      <div class="form-container">

       <!-- <div class="embed-responsive embed-responsive-16by9"  id="display" style="width: 400px; height: 300px;">
        <iframe class="embed-responsive-item"  src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen></iframe>
      </div> -->
      <div class="embed-responsive embed-responsive-16by9" id="display" style="width: 400px; height: 300px;">
        <iframe class="embed-responsive-item" src="http://197.166.79.134:8080" allowfullscreen></iframe>
    </div>


    </div>
    </div>


    <script>
      var buildUrl ='{% static  "Build1" %}';
      var loaderUrl = buildUrl + "/final project.loader.js";
      var config = {
        dataUrl: buildUrl + "/final project.data",
        frameworkUrl: buildUrl + "/final project.framework.js",
        codeUrl: buildUrl + "/final project.wasm",
        streamingAssetsUrl: "StreamingAssets",
        companyName: "DefaultCompany",
        productName: "ZU_laboratory",
        productVersion: "1.0",
      };

      var container = document.querySelector("#unity-container");
      var canvas = document.querySelector("#unity-canvas");
      var loadingBar = document.querySelector("#unity-loading-bar");
      var progressBarFull = document.querySelector("#unity-progress-bar-full");
      var fullscreenButton = document.querySelector("#unity-fullscreen-button");
      var mobileWarning = document.querySelector("#unity-mobile-warning");

      // By default Unity keeps WebGL canvas render target size matched with
      // the DOM size of the canvas element (scaled by window.devicePixelRatio)
      // Set this to false if you want to decouple this synchronization from
      // happening inside the engine, and you would instead like to size up
      // the canvas DOM size and WebGL render target sizes yourself.
      // config.matchWebGLToCanvasSize = false;

      if (/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)) {
        container.className = "unity-mobile";
        // Avoid draining fillrate performance on mobile devices,
        // and default/override low DPI mode on mobile browsers.
        config.devicePixelRatio = 1;
        mobileWarning.style.display = "block";
        setTimeout(() => {
          mobileWarning.style.display = "none";
        }, 5000);
      } else {
        canvas.className = "responsive";
        // canvas.style.height = "760px";
      }
      canvas.style.background = "url('" + buildUrl + "/final project.jpg') center / cover";
      loadingBar.style.display = "block";

      var script = document.createElement("script");
      script.src = loaderUrl;
      script.onload = () => {
        createUnityInstance(canvas, config, (progress) => {
          progressBarFull.style.width = 100 * progress + "%";
        }).then((unityInstance) => {
          loadingBar.style.display = "none";
          fullscreenButton.onclick = () => {
            unityInstance.SetFullscreen(1);
          };
        }).catch((message) => {
          alert(message);
        });
      };
      document.body.appendChild(script);
    </script>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>


  </body>
</html>

labs/templates/labs/lab_detail.html
{% extends "base.html" %}
{% load static %}
{% block body %}



<body>



    <br />

    <header class="margin-Top">



        <div class="">


            <h4 class="center wow animate__flash">
              explore our simulation labs
            </h4>
            <br />

        </div>

    </header>

    <br />


    <section class="Lab1Details blogs">

        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-7 col-md-12 col-sm-12">

                    <div class="card mb-3 shadow p-3 mb-5 bg-white rounded">
                        <img src='{{lab.image.url}}' class="card-img-top" alt="Logo" height="500px;"><!-- loading this specific lab image form DB -->
                        <div class="card-body">
                            <h5 class="card-title"><b style="font-family: fantasy;" class="text-muted"> {{lab.title}}</b> </h5><!-- loading this specific lab title form DB -->
                            <p class="card-text">
                              {{lab.description|safe}} <!-- loading this description lab image form DB -->
                            </p>


                            <h5 class="card-title"><b style="font-family: fantasy;" class="text-muted">Experiment Objective  </b> </h5>
                            <p class="card-text">
                                {{lab.experiment_objective|safe}}<!-- loading this objective lab image form DB -->
                            </p>

                            <h5 class="card-title"><b style="font-family: fantasy;" class="text-muted"> Experiment Materials</b></h5>
                            <p class="card-text">
                                {{lab.experiment_materials|safe}}<!-- loading this mateials lab image form DB -->
                            </p>


                            <h5 class="card-title"><b style="font-family: fantasy;" class="text-muted">Experiment Steps</b> </h5>
                            <p class="card-text">
                                {{lab.experiment_steps|safe}}<!-- loading this specific steps image form DB -->
                            </p>

                            <h5 class="card-title"><b style="font-family: fantasy;" class="text-muted">Experiment Conclusion</b></h5>
                            <p class="card-text">
                                {{lab.experiment_conclusion|safe}}<!-- loading this specific lab Conclusion form DB -->
                            </p>


                            <p class="card-text"><small class="text-muted" class="text-muted">{{lab.created_at}}</small></p><!-- loads the date creation of this app -->
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-12 col-sm-12">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="{{lab.youtube_url}}" allowfullscreen></iframe><!-- opens specific youtuber url for the experiment -->

                    </div>

                    <br />
                    <!-- <button type="button" class="btn btn-secondary btn-lg btn-block" style="margin-bottom:20px;">Try Our Experiment Now</button> -->

                    <a role="button" class="btn btn-secondary btn-lg btn-block" href="{% url 'labs:unity_lab' lab_id=lab.id %}" aria-pressed="true" style="margin-bottom:20px;">Try Our Experiment Now</a> </div>
                    <!-- redirects the user to the unity page -->
                <br />
            </div>
        </div>



    </section>

{% endblock body %}

labs/templates/labs/lab_list.html
{% extends "base.html" %}
{% load static %}
{% block body %}


<title>virtual labs</title>



<body class="Virtual-labs mt-5">
  <section class="">
    <div class="container translate mt-5">

      <h4 class="center wow animate__flash mb-5">
        explore our simulation labs
      </h4>

      <div class="row MarginFromLeft">

        {% for lab in lab_list %}   <!--for every lab in the website, it will has these attributes loaded from models -->

        <div class="col-sm-12 col-md-6 col-lg-4 padding-bot">

          <img src='{{lab.image.url}}' class="img-fluid rounded-circle img-thumbnail" style="width: 230px; height: 230px; " alt="image">
            <!-- loading this specific lab image form DB -->

          <div class="" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title" >{{lab.title}}</h5> <!-- loading this specific lab title form DB -->
              <tag class="text-muted"></tag>
              <p class="card-text">
                {{lab.description|safe|truncatewords:10}} <!-- loading this specific lab description form DB -->
              </p>
              <a href="{% url 'labs:lab_detail' slug=lab.slug %}" class="btn btn-info" style="margin-left: 50px;">Read More</a><!--redircting the user to the chosen lab_detail page -->
            </div>
          </div>
        </div>
        {% endfor %}
      </div>


      <nav aria-label="Page navigation example">
        {% if is_paginated %}
        {% load i18n %}
        <div class="pagination">
        {% if page_obj.has_previous %}
        <a href="?page{{ page_suffix }}={{ page_obj.previous_page_number }}{{ getvars }}{{ hashtag }}" class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a>
        {% else %}
        <span class="disabled prev">&lsaquo;&lsaquo; {% trans "previous" %}</span>
        {% endif %}
        {% for page in pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?page{{ page_suffix }}={{ page }}{{ getvars }}{{ hashtag }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <a href="?page{{ page_suffix }}={{ page_obj.next_page_number }}{{ getvars }}{{ hashtag }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>
        {% else %}
        <span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span>
        {% endif %}
        </div>
        {% endif %}
      </nav>


    </div>

  </section>
</body>

  {% endblock body %}