about/urls.py
from django.urls import path
from .views import AboutList, FAQ


app_name = 'about'

urlpatterns= [
   path('', AboutList.as_view(), name='about'),
   path('FAQ/', FAQ.as_view(), name='FAQ'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns= [
   path('signup/', views.signup, name='signup'),
   path('profile/', views.profile, name='profile'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns= [
   path('',views.PostList.as_view(),name='post_list'),
   path('<slug:slug>',views.PostDetail.as_view(),name='post_detail'),
]

chatbotpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('chatbotapp.urls'))

]

contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns= [
   path('', views.send_email, name='contact'),
]

labs/urls.py
from django.urls import path
from . import views

app_name = 'labs'

urlpatterns = [
    path('', views.LabList.as_view(), name='lab_list'),
    path('unity_lab/<int:lab_id>/', views.unity_lab, name='unity_lab'),
    path('<slug:slug>',views.LabDetail.as_view(),name='lab_detail'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # accounts must be at first of all
    path('accounts/', include('django.contrib.auth.urls')), # User Auth
    path('accounts/', include('accounts.urls', namespace='accounts')), # Profile
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')), # summernote package for text editor in admin
    path('', include('settings.urls', namespace='home')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('labs/', include('labs.urls', namespace='labs')),
    path('blog/', include('blog.urls', namespace='blog')),

    # social account
    path('socialaccounts/', include('allauth.urls')),

    path('verification/', include('verify_email.urls')), # verify pkg


]

# settings for static and media roots
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% url 'contact:contact' as contact %}
{% url 'accounts:profile' as profile %}


<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'wowJs/css/libs/animate.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <script src="https://kit.fontawesome.com/b89b4b2308.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/App.js' %}"></script>
    <script type="text/javascript" src="{% static 'wowJs/dist/wow.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    {% if request.path == contact %}
      <link rel="stylesheet" href="{% static 'css/styleContact.css' %}">  
    {% endif %}

     {% if request.path == profile %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    {% endif %}
        
    

    <title>Taleen</title>

    <script>
        new WOW().init();
    </script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top ">
        <a class="navbar-brand margin-left Left" href="#"><img src="{{myfooter.logo.url}}"
                style="width: 60px; height:60px" alt="Taleen"></a>
        <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon flex-md-shrink-0"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto ml-5 underline Left control flex-md-shrink-0 " style="margin-trim: 0;">
                <li class="nav-item ">
                    <a class="nav-link " href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'labs:lab_list' %}">Virtual labs</a>
                </li>

                <li class="nav-item ">
                    <a class="nav-link " href="{% url 'blog:post_list' %}">Blogs</a>
                </li>

                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'about:about' %}">About us</a>
                </li>

                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'contact:contact' %}">Contact us</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown adjusting dropdown-menu-right dropdown-menu-lg-left"
                style="list-style-type: none; padding-right: 80px;">
                <a class="nav-link dropdown-toggle" style="color: #8da3a5;" href="#" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle "></i>
                </a>
                <div class="dropdown-menu" style="background-color: #ecf0f1;" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'accounts:profile' %}">profile</a>
                    <a class="dropdown-item" href="{% url 'about:FAQ' %}">FAQ</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">log out</a>
                </div>
            </li>
            {% else %}
            <div class="my-2 my-lg-0 ">
                <a href="{% url 'accounts:signup' %}" class="btn btn-outline-secondary my-2 my-sm-0" role="button"
                    aria-pressed="true" target="_blank">Register</a>
                <a href="{% url 'login' %}" class="btn btn-outline-secondary myMoving" role="button" aria-pressed="true"
                    target="_blank">Login</a>
            </div>
            {% endif %}
        </div>
    </nav>

    <!-- content of pages -->
    {% block body %}
    <!-- content of pages -->
    {% endblock body %}

    <footer class="bg-footer text-white text-center text-lg-start ">
        <!-- Grid container -->
        <div class=" p-4">
            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
                    <img src="{% static 'images/molecule.png' %}" class="rounded-circle" alt="logo"
                        style="width: 60px; height:60px">
                    <br /> <br />
                    <h5 class="text-uppercase text-white">{{myfooter.name}}</h5>

                    <p>
                        {{myfooter.description}}
                    </p>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-5 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-white">HAVE A QUESTIONS?</h5>


                    <div class="">
                        <i class="fas fa-map-marker-alt "></i>
                        <!-- <img src="..." class=" " alt="..."> -->
                        <div class="media-body">
                            <h5 class="mt-0"></h5>
                            <p>{{myfooter.Address}}</p>
                        </div>

                    </div>
                    <div class="">
                        <i class="fas fa-phone-alt"></i>
                        <!-- <img src="..." class="" alt="..."> -->
                        <div class="media-body">
                            <h5 class="mt-0"></h5>
                            <p>{{myfooter.phone}}</p>
                        </div>
                    </div>

                    <div class="">
                        <i class="fas fa-envelope"></i>
                        <!-- <img src="..." class="" alt="..."> -->
                        <div class="media-body">

                            <p>{{myfooter.email}}</p>
                        </div>
                    </div>

                </div>
                <!--Grid column-->
                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0 mt-0">
                    <!-- <h5 class="text-uppercase mb-0">Links</h5> -->
                    <br />
                    <p class=""><strong>Subscribe to our newsletter to get the latest news</strong></p>
                    <form id="subscribe_form_id" method="POST" action="{% url 'home:subscribe' %}" novalidate>
                        {% csrf_token %}
                        <div class="input-group ">
                            {{ subscriber_form }}
                            <button class="btn btn-warning" type="submit">Subscribe</button>
                        </div>
                    </form>
                    <div id="message"></div>
                </div>
                <script src="https://code.jquery.com/jquery-3.6.0.min.js"
                    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
                <script>
                    $("#subscribe_form_id").submit(function (e) {
                        e.preventDefault();

                        var form = $(this);
                        var url = form.attr("action");

                        $.ajax({
                            url: url,
                            type: 'POST',

                            data: form.serialize(),
                            dataType: 'json',
                            success: function (data) {
                                //console.log(data.response_message); //for test
                                document.getElementById("message").innerText = data
                                    .response_message;
                            }
                        });
                    });
                </script>
                <!--Grid column-->
            </div>
            <!--Grid row-->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            © 2021 Copyright:
            <a class="text-white" href="/">Virtual-Lab</a>
        </div>
        <!-- Copyright -->
    </footer>

    <div>
        <button type="button" id="btnScroll" class="btn btn-info rounded-circle" onclick="toUp()"><i
                class="fas  fa-arrow-circle-up fa-2x"></i></button>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/pluign.js' %}"></script>
</body>

</html>